apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: 828023602172.dkr.ecr.eu-central-1.amazonaws.com/reservations:latest
          name: reservations
          env:
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3001'
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
          ports:
            - containerPort: 3004
